Repository beyond-sw-camp/be04-1st-yeonbong_1Jo_NaN_NULL_joahaeTeam-koongya_academy, pull requests merged in 2024-01, with the labels that each got.

#21 DML 수정
  README.md
Labels: enhancement

#20 CRUD-Read 수정
  README.md
Labels: documentation

#27 '목차로 돌아가기' 추가
  README.md
Labels: documentation

#30 README.md - WBS 이미지 업데이트
  README 90456e44faab4013bf4520930090a7ab/Untitled.png
Labels: documentation

#32 fr-4,6,7 사진 변경
  README 90456e44faab4013bf4520930090a7ab/ezgif.com-video-to-gif-converter_(5).gif
  README 90456e44faab4013bf4520930090a7ab/ezgif.com-video-to-gif-converter_(5).gif.gif
  README 90456e44faab4013bf4520930090a7ab/fr06.gif
  README 90456e44faab4013bf4520930090a7ab/fr07.gif
Labels: documentation

#34 README.md 회의록 수정
  README.md
Labels: documentation, enhancement

#39 .damx 파일 업데이트
  README 90456e44faab4013bf4520930090a7ab/KoongyaAcademy.damx
Labels: documentation

#40 README.md - 240101 스터디 수정
  README 90456e44faab4013bf4520930090a7ab/Untitled 10.png
  README.md
Labels: documentation
